### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by andrejkaurin** [js-data/js-data#280]
On local environment everything is working just fine. Uploaded on server (ubuntu) I am getting the error bellow. All files are 100% there. Any idea on what's the issue?

On the critical line there is a following code
```javascript

// req.body is populated with username and password
  User.findAll({username: req.body.username, password: req.body.password}).then(function() {
 ....
})
```

and User looks like this

```javascript
var JSData = require('js-data');
var DSSqlAdapter = require('js-data-sql');

// here is connection part with database params

var store = new JSData.DS();
module.exports =store.defineResource({
  name: 'user'
});

```
```javascript
TypeError: undefined is not a function
    at DS.findAll (/usr/lcma-ui/node_modules/js-data/dist/js-data-debug.js:4850:11)
    at Defaults.def.(anonymous function) [as findAll] (/usr/lcma-ui/node_modules/js-data/dist/js-data-debug.js:3719:30)
    at exports.login (/usr/lcma-ui/server/api/auth/auth.controller.js:97:6)
    at Layer.handle [as handle_request] (/usr/lcma-ui/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/lcma-ui/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/usr/lcma-ui/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/usr/lcma-ui/node_modules/express/lib/router/layer.js:82:5)
    at /usr/lcma-ui/node_modules/express/lib/router/index.js:234:24
    at Function.proto.process_params (/usr/lcma-ui/node_modules/express/lib/router/index.js:312:12)
    at /usr/lcma-ui/node_modules/express/lib/router/index.js:228:12
    at Function.match_layer (/usr/lcma-ui/node_modules/express/lib/router/index.js:295:3)
    at next (/usr/lcma-ui/node_modules/express/lib/router/index.js:189:10)
    at Function.proto.handle (/usr/lcma-ui/node_modules/express/lib/router/index.js:165:3)
    at router (/usr/lcma-ui/node_modules/express/lib/router/index.js:34:12)
    at Layer.handle [as handle_request] (/usr/lcma-ui/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/usr/lcma-ui/node_modules/express/lib/router/index.js:270:13)
```

**Comment by jmdobry** [comment]
Whatever JavaScript environment you're using to execute your program is missing a global `Promise` constructor.

**Comment by andrejkaurin** [comment]
Problem is on server side: NodeJS, Express.
