### ISSUE TITLE
Problem running js-data tests.

### ISSUE THREAD

**Issue by krio** [js-data/js-data#306]
When I try to run npm test I get the error below. I followed the instructions for contributing. I'm running node 4.3.1 LTS. There's a couple of posts about it related to babel-eslint, but I haven't been able to dig into it yet. Have you run into this yet?

```
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/Krio/Documents/js_data/js-data/node_modules/babel-eslint/index.js:201:40)
    at Object.exports.parse (/Users/Krio/Documents/js_data/js-data/node_modules/babel-eslint/index.js:374:5)
    at parse (/Users/Krio/Documents/js_data/js-data/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:528:27)
    at EventEmitter.module.exports.api.verify (/Users/Krio/Documents/js_data/js-data/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:652:19)
    at processText (/Users/Krio/Documents/js_data/js-data/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:225:27)
    at processFile (/Users/Krio/Documents/js_data/js-data/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:262:18)
    at executeOnFile (/Users/Krio/Documents/js_data/js-data/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:609:23)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/Krio/Documents/js_data/js-data/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:632:56)
    at /Users/Krio/Documents/js_data/js-data/node_modules/standard/node_modules/standard-engine/index.js:105:56
```

**Comment by jmdobry** [comment]
I saw that a few times, and I think it was because some dependencies weren't installed. What branch are you trying to build?

**Comment by krio** [comment]
This was master. V3 seems to work OK.
