### ISSUE TITLE
Bug when querying mapper with relations, with arg with

### ISSUE THREAD

**Issue by jshrt** [js-data/js-data#500]
## Description

Upon querying a mapper like the following:

```
const post = await store.find('posts', '1', { with: 'user' })
```
The following error is thrown:
```
err: TypeError: list.forEach is not a function
    at Object._getIndex (/home/jshrt/Workspace/projects/invisible/research/js-orm/js-data-orm-test/node_modules/js-data/dist/js-data.js:265:10)
    at Object._forRelation (/home/jshrt/Workspace/projects/invisible/research/js-orm/js-data-orm-test/node_modules/js-data/dist/js-data.js:226:24)
    at /home/jshrt/Workspace/projects/invisible/research/js-orm/js-data-orm-test/node_modules/js-data/dist/js-data.js:894:13
    at Array.forEach (<anonymous>)
    at Object.forEachRelation (/home/jshrt/Workspace/projects/invisible/research/js-orm/js-data-orm-test/node_modules/js-data/dist/js-data.js:893:18)
    at SqlAdapter.loadRelationsFor (/home/jshrt/Workspace/projects/invisible/research/js-orm/js-data-orm-test/node_modules/js-data-sql/node_modules/js-data-adapter/dist/js-data-adapter.js:1059:20)
    at /home/jshrt/Workspace/projects/invisible/research/js-orm/js-data-orm-test/node_modules/js-data-sql/node_modules/js-data-adapter/dist/js-data-adapter.js:970:21
    at <anonymous>
```

Also, I've noticed some rather vague validation errors that go like *Validation Failed* without mentioning what field or why.

I was testing module so that maybe I could use it in production, the APIs and the extensiblity in this module is terrific! good job! I just love how flexible I can be with it but I am not sure that the thing is even stable...

I'm really interested in giving js-data a try, but any guarantees when it comes to stability, specially for basic functionality such as relations and querying relations...

## Steps to reproduce

```
'use strict'

const { Container } = require('js-data')
const { SqlAdapter } = require('js-data-sql')

// Create an instance of SqlAdapter
const adapter = new SqlAdapter({
	knexOpts: {
		client: 'postgres',
		connection: {
			host: '0.0.0.0',
			port: '5432',
			user: 'knex',
			password: 'knexy',
			database: 'jsdatatest'
		}
	}
})

// Other JSData setup hidden

const store = new Container()

store.registerAdapter('sql', adapter, { default: true })

store.defineMapper('users', {
	schema: {
		properties: {
			id: {
				type: 'string'
			}
		}
	},
	relations: {
		hasMany: {
			posts: {
				foreignKey: 'user_id',
				localField: 'posts',
			}
		}
	}
})

store.defineMapper('posts', {
	schema: {
		properties: {
			id: {
				type: 'string'
			},
			user_id: {
				type: 'string'
			}
		}
	},
	relations: {
		belongsTo: {
			user: {
				foreignKey: 'user_id',
				localField: 'user'
			}
		}
	}
})

const createUser = id => store.create('users', { id })
const createPost = (id, user_id) => store.create('posts', { id, user_id })

const fn = async () => {
	try {
		const post = await store.find('posts', '1', { with: 'user' })
		console.log(post)
	} catch (err) {
		console.log({ err })
	}
}

fn()
```

Thanks!

**Comment by mikeu** [comment]
I haven't actually tried running your code @jshrt , but I have a couple of comments that might help, depending how close this is to what you're actually running...

First, you seem to be defining functions to create users and posts, but never actually calling them. This shouldn't be the cause of the error you are encountering, but is probably still worth fixing while trying to get things working, since it will mean that your data store will be empty.

Second, you define a mapper for `users` records but then say that a `posts` record belongs to a `user` record instead. You also use the singular instead of the plural when requesting the posts `with: 'user'`.

Does either of those points shed any light on your issue? I'm also quite new to working with js-data so I'm afraid I can't comment on your larger questions about stability, but I _can_ say that I've had good luck so far working with multiple interconnected schemas, so it should definitely be possible to get this straightforward example up and running.

**Comment by mikeu** [comment]
It turns out, at least as far as the documentation is concerned, that we may both be right as far as the [`with` argument](http://www.js-data.io/v3.0/docs/relations#section-eagerly-loading-relations) is concerned:

>  The `with` option should be an array of strings, which are either the `name` of a related Mapper, or the `localField` where a relation is defined.

However, I think the other part of that point still stands. As far as I'm aware, the relationship in your `posts` mapper should be the same as the name of the mapper:
```javascript
belongsTo: {
  users: {
    // ...
  }
}
```
Does that make any difference?

In my relatively limited experience with js-data so far, I would agree with your assessment about its current state. I think it works quite well on the whole when used as intended, but it is not yet great at telling the developer why something has failed when used otherwise.
